name: CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  simple-check:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show system info
        run: |
          echo "Running CI"
          systeminfo
          dir
        shell: powershell

  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod tidy
        shell: bash

      - name: Build project
        run: go build ./...
        shell: bash

      - name: Run tests
        run: go test ./... -v
        shell: bash
