name: CI

on:
  push:
    branches: [ "main", "development", "release" ]
  pull_request:
    branches: [ "main", "development", "release" ]

jobs:
  simple-check:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show system info
        run: |
          echo "Running CI"
          systeminfo
          dir
        shell: powershell

  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install dependencies
        run: go mod tidy
        shell: bash

      - name: Build project
        run: go build ./...
        shell: bash

      - name: Run tests
        run: go test ./... -v
        shell: bash

      - name: Install Doxygen
        run: winget install --id Doxygen.Doxygen -e --accept-package-agreements --accept-source-agreements
        shell: powershell

      - name: Download Doxygen
        run: |
          $url = "https://doxygen.nl/files/doxygen-1.9.9.windows.x64.zip"
          $out = "$env:TEMP\doxygen.zip"
          Invoke-WebRequest $url -OutFile $out
          Expand-Archive $out -DestinationPath "C:\doxygen"
          $env:PATH += ";C:\doxygen\bin"
        shell: powershell


      - name: Generate Doxygen docs
        run: doxygen Doxyfile
        shell: powershell

